spring:
  application:
    name: problem-service
  profiles:
    include:
      - common
      - web
server:
  port: 8082
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
