spring:
  application:
    name: user-service
  profiles:
    include:
      - common
      - web
server:
  port: 8081
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
jwt:
  secret: ${JWT_SECRET:study-platform-jwt-secret-key-must-be-256bit-or-more!!}
  expiration-ms: 86400000
