spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: problem-service
              uri: http://problem.backend.svc.cluster.local:8080
              predicates:
                - Path=/api/v1/problem/**

            - id: user-service
              uri: http://user-manage.backend.svc.cluster.local:8080
              predicates:
                - Path=/api/v1/user/**

            - id: chapter-service
              uri: http://chapter.backend.svc.cluster.local:8080
              predicates:
                - Path=/api/v1/chapter/**

            - id: user-service-internal
              uri: http://user-manage.backend.svc.cluster.local:8080
              predicates:
                - Path=/internal/v1/user/**

            - id: problem-service-internal
              uri: http://problem.backend.svc.cluster.local:8080
              predicates:
                - Path=/internal/v1/problem/**

            - id: problem-api-docs
              uri: http://problem.backend.svc.cluster.local:8080
              predicates:
                - Path=/api-docs/problem
              filters:
                - RewritePath=/api-docs/problem, /api-docs

            - id: user-api-docs
              uri: http://user-manage.backend.svc.cluster.local:8080
              predicates:
                - Path=/api-docs/user
              filters:
                - RewritePath=/api-docs/user, /api-docs

            - id: chapter-api-docs
              uri: http://chapter.backend.svc.cluster.local:8080
              predicates:
                - Path=/api-docs/chapter
              filters:
                - RewritePath=/api-docs/chapter, /api-docs

eureka:
  client:
    enabled: false
