spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: problem-service
              uri: lb://problem-service
              predicates:
                - Path=/api/v1/problem/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/user/**

            - id: chapter-service
              uri: lb://chapter-service
              predicates:
                - Path=/api/v1/chapter/**

            - id: user-service-internal
              uri: lb://user-service
              predicates:
                - Path=/internal/v1/user/**

            - id: problem-service-internal
              uri: lb://problem-service
              predicates:
                - Path=/internal/v1/problem/**

            - id: problem-api-docs
              uri: lb://problem-service
              predicates:
                - Path=/api-docs/problem
              filters:
                - RewritePath=/api-docs/problem, /api-docs

            - id: user-api-docs
              uri: lb://user-service
              predicates:
                - Path=/api-docs/user
              filters:
                - RewritePath=/api-docs/user, /api-docs

            - id: chapter-api-docs
              uri: lb://chapter-service
              predicates:
                - Path=/api-docs/chapter
              filters:
                - RewritePath=/api-docs/chapter, /api-docs

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
