spring:
  application:
    name: api-gateway
  profiles:
    include:
      - common
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
server:
  port: 8080
springdoc:
  swagger-ui:
    urls:
      - name: problem-service
        url: /api-docs/problem
      - name: user-service
        url: /api-docs/user
      - name: chapter-service
        url: /api-docs/chapter
