apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: backend
type: Opaque
stringData:
  DB_HOST: "host.docker.internal"
  DB_PORT: "3306"
  DB_NAME: "TEST"
  DB_USER: "test"
  DB_PASSWORD: "test"
  REDIS_HOST: "host.docker.internal"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "study1234"
  JWT_SECRET: "your-jwt-secret"
