apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration
  namespace: backend
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: flyway
          image: flyway:latest
          imagePullPolicy: Never
          command: ["java", "-jar", "app.jar"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD